model:
  _target_: src.model.GwcNet.GwcNet
  maxdisp: 192
  use_concat_volume: False
  feature: raw
  syncBN: True
loss:
  _target_: src.model.GwcNet.GwcLoss
  weights:
    - 0.5
    - 0.5
    - 0.7
    - 1.0
  maxdisp: 192
  mask: True
